### ISSUE TITLE
add workshop

### ISSUE THREAD

**Issue by takahitomiyamoto** [japandreamin/web#5]
@shunkosa 
sessions のマークダウン内で
```
format: workshop 
```
を指定したいです。

**Comment by shunkosa** [comment]
https://github.com/japandreamin/web/blob/master/themes/ohana-theme-hugo/src/style/partials/_type.scss
https://github.com/japandreamin/web/blob/master/themes/ohana-theme-hugo/layouts/sessions/list.html
